# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f29ad8f038a53dddbd8d570939438bba"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "justFab-ext"
handle = "justfab-ext"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers, read_products, write_cart_transforms, write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "plustestpcoch.myshopify.com"
include_config_on_deploy = true

